### ISSUE TITLE
Support for llama.cpp API Server

### ISSUE THREAD

**Issue by digiwombat** [anon998/simple-proxy-for-tavern#8]
Firstly, thanks for your hard work on this project so far! llama.cpp has added an API that can be built into an .exe. Support for it would be much appreciated.

https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md#api-endpoints

Endpoints are pretty simple. It has some nodejs examples. Seems pretty cozy. I'd slap together a PR, but I am swamped at the moment.

**Comment by digiwombat** [comment]
Thanks for slapping this together. You're a champion. I did some testing with things and wiggled some settings around. There are a number of undocumented params you can pass on generate (all the gpt_params settings work) and the problem child for basic gens for anyone who comes around to do testing was repeat_last_n. It was set to 64 tokens.

Setting the repeat_last_n in the config to `repeat_last_n: 1028` clears the problem up entirely, as far as I can tell. Though I was only testing again the `default` preset.

Here are the undocumented parameters for anyone tinkering:  
https://github.com/ggerganov/llama.cpp/blob/master/examples/common.h#L23  
https://github.com/ggerganov/llama.cpp/blob/master/examples/server/server.cpp#L138 

To the broader problem, the server is definitely running it like a console app and just appending context instead of reprocessing or doing anything clever. A few questions and responses quickly runs into the `Context too long` error.

I added a disgusting hack to the server.cpp file to make it work consistently, though it does force reprocessing the entire prompt every time. Basically at the top of `bool LoadPrompt()` I added:

```cpp
if(processed_tokens.size() != 0)
{
    processed_tokens.erase(processed_tokens.begin() + 1, processed_tokens.end());
}
if(embd_inp.size() != 0)
{
    embd_inp.erase(embd_inp.begin() + 1, embd_inp.end());
}

n_remain = 0;
n_past = 0;
n_consumed = 0;
```

That'll get it working for any testing, but it is a cudgel instead of a scalpel. I will maybe spend a little time seeing what I can do to cut down on reprocessing. I don't think the proxy will require anymore changes, so I'll just close this and comment if I come across anything good.

**Comment by digiwombat** [comment]
Apologies, Anon. Just going to re-open this for information sake since it's still pretty snappy even with the reprocessing.

**Comment by digiwombat** [comment]
Whoops, good catch. Fixed that. Being a lazy copy-paste goblin got the better of me.

**Comment by digiwombat** [comment]
I'm about to eat dinner, but I'll take a look at this after and test them out. Thanks for actually reading through the code. I also forgot to change reload_ctx to a bool, so it's sort of impressive that worked. I guess the get<> stuff doesn't care too much.

**Comment by digiwombat** [comment]
Okay, looks like they're doing a refactor on the that will hopefully take care of all these concerns. And they added server to the build actions earlier as well, so it will be easy to point people at the server once the improved version is in. 👍🏻

**Comment by FSSRepo** [comment]
Thank you very much for improving the code. I apologize for my bad practices in C++. I'm not very good at that language.

**Comment by digiwombat** [comment]
No worries and thanks to @anon998 for looking through the code more thoroughly. Thanks for putting the server together and getting the ball rolling in the first place. There's a lot of value in that. And since it's in the default build actions now, I think it will help a lot of people get native speeds.

**Comment by LiliumSancta** [comment]
I'm testing the generation and it seems to have a problem with the generated size and i believe the best place would be here.
There is something strange with the size sent to llama.cpp in n_predict the value being sent in my test is "n_predict":1014 i set maxNewTokens: 40 i know it must be due to today's changes, stoppingStrings don't seem to be working either , but this I still need to check better and maybe it's something in llama.cpp

**Comment by digiwombat** [comment]
He is setting it like this:

```js
n_predict: Math.min(
      config.promptTokenCount + 1 + genParams.max_length,
      config.maxContextLength
    ),
```

So I'm pretty sure n_predict/maxTokens isn't being used at all. And yeah, I'm not sure about the stopping strings. That could be a llama.cpp issue. There's certainly code in the server to catch llama_eos_token(), it just doesn't seem to want to generate one. I don't know if that's a generation settings issue or what.

**Comment by LiliumSancta** [comment]
Yes, if you manually set llama.params.n_predict = body["n_predict"].get<int>(); will respect the maximum size. As for stopsStrings, I'm going to test with another model/prompt because I'm using guanaco with a template i created and there may be something wrong with the stop word. I'll try some things later, now I've had a few drinks and I'm prone to making some mistakes 😅. Anyway, good job, makes using frontends a lot easier with llama.cpp without relying on python.

**Comment by digiwombat** [comment]
Deleted what I was typing. Looks like anon might have caught the problem. We'll see.

**Comment by digiwombat** [comment]
llama.cpp server seems to be working as expected now so I guess we can close this. ( ͡° ͜ʖ ͡°)

Thanks @anon998 for all the contributions. Apologies for dragging you into what turned out to be a much larger project than expected. Haha.
